name: Run Testsuite (manual) # Unfortunately, we cannot modify the name: https://github.community/t/github-actions-dynamic-name-of-the-workflow-with-workflow-dispatch/150327
on:
  workflow_dispatch:
    inputs:
      suites:
        description: 'Comma seperated testsuites to execute'
        required: true
        type: string
      build_args:
        description: 'Build arguments, if not specified defaults will be taken'
        required: false
        type: string
      system_tests_branch:
        description: 'Branch to take the system tests from (tools/tests/)'
        default: 'develop'
        required: true
        type: string
      log_level:
        description: 'Logging verbosity level used for the systemtests'
        default: 'INFO'
        required: true
        type: choice
        options:
            - 'DEBUG'
            - 'INFO'
            - 'WARNING'
            - 'ERROR'
            - 'CRITICAL'
      upload_artifacts:
        description: 'Upload artifacts also on success (not only on failure)'
        default: 'TRUE'
        type: choice
        options:
            - 'FALSE'
            - 'TRUE'

jobs:
  run_testsuite_manual:
    uses: ./.github/workflows/run_testsuite_workflow.yml
    with: 
      suites: ${{ inputs.suites }}
      build_args: ${{ inputs.build_args }}
      system_tests_branch: ${{ inputs.system_tests_branch }}
      log_level: ${{ inputs.log_level }}
      upload_artifacts: ${{ inputs.upload_artifacts }}
