name: System tests cleanup

on:
  schedule:
    - cron: "0 3 1 * *"
  workflow_dispatch:

jobs:
 cleanup-system-tests-runner:
    name: Cleanup system tests runner
    runs-on: [self-hosted, linux, x64, precice-tests-vm]
    steps:
      - name: Report disk usage before cleanup
        run: |
          df -h | grep -E '(Filesystem|/var)'
      - name: Run docker system prune
        run: |
          docker system prune --all --force
      - name: Report disk usage after cleanup
        run: |
          df -h | grep -E '(Filesystem|/var)'
